### ISSUE TITLE
Add License information to the repo

### ISSUE THREAD

**Issue by BartWojtowicz** [BartWojtowicz/videopython#4]

**Comment by bartoszrud** [comment]
I suggest using an Apache 2.0 license as in this license contributors provide an express grant of patent rights. Moreover, it explicitly states that it doesn't grant trademark rights.

**Comment by BartWojtowicz** [comment]
> I suggest using an Apache 2.0 license as in this license contributors provide an express grant of patent rights. Moreover, it explicitly states that it doesn't grant trademark rights.

Sounds good, let's do it
